### ISSUE TITLE
Question: why do not use events.forEach in emit() function?

### ISSUE THREAD

**Issue by Daymannovaes** [browserify/events#81]
Hi,

I have a question about best practices.

I'm trying to implement my own event emitter, and I was using the following code:

```javascript
const length = listeners.length;
for (let i = 0, i < length; i++) {
    listeners[i].call(this, event);
}
```

But this throws an error if some listener removes itself because it'd change the array length while looping through the listeners.

So I decide to change to a forEach, something like:

```javascript
listeners.forEach((listener) => listener.call(this, event));
```

And worked like a charm! But I did some research on some EventEmitter polyfills, and no one uses this pattern. Everyone uses an array clone pattern, and iterate with a `for`.

There's a specific reason to choose this pattern over another?

Thanks!

**Comment by Daymannovaes** [comment]
Possible reasons that I could think of:

### Performance
It's common sense that `for` statement is more performatic than `forEach`. But I ran some benchmarks test, and I got a surprising result. Apparently modern browsers are optimized for the second case now:

_Run at https://jsbench.me/_
![image](https://user-images.githubusercontent.com/3648665/108845825-a6f04e00-75bc-11eb-8758-1760fc18c8a5.png)

_Run at https://jsben.ch/_
![image](https://user-images.githubusercontent.com/3648665/108846002-ddc66400-75bc-11eb-8384-c2ade2a6360e.png)



### Compatibility
`ForEach` is widely implemented. It has support in 95% of all environments, against 96% of the `for` statement.

![image](https://user-images.githubusercontent.com/3648665/108845515-495c0180-75bc-11eb-8a4b-829db5c03067.png)
![image](https://user-images.githubusercontent.com/3648665/108845590-609aef00-75bc-11eb-888f-b28ba897a5ae.png)

**Comment by goto-bus-stop** [comment]
For this package the answer is "because node.js does it", and this is a straight port of the Node.js built in module. Changes are made exclusively to broaden browser support.

Your benchmark uses a single listener array of 1000 listeners which is quite unusual. 99% of the time, there will only be a small amount of listeners for an event, usually just 1. The benchmark might look different if you have less than 10 listeners vs. 1000. Though either way, this module values compatibility over performance :)

**Comment by Daymannovaes** [comment]
Right. So, you have any clue on why node choose this pattern?

**Comment by goto-bus-stop** [comment]
Maybe my edit didn't come through email—if you use forEach() you still need to clone first.

That + the performance characteristics possibly being different for small arrays could mean it's not faster to use forEach in the typical case.

**Comment by Daymannovaes** [comment]
You're correct.

Although, if we clone the array first, we could still use the `forEach()` approach.

For example:
```javascript
listeners.slice().forEach(listener => listener());
```

**Comment by goto-bus-stop** [comment]
You could, but it's not what Node.js does, probably because it's slower.

I get this:
![image](https://user-images.githubusercontent.com/1006268/109394176-ec4aad80-7925-11eb-8e29-86737bac9630.png)

I used a short array of 3 listeners, which is probably already more than the median.

**Comment by Daymannovaes** [comment]
Ok, thanks for helping me.

I'll close the issue since my questions are solved.
